# docker-compose up --build
# docker-compose up down
# docker-compose up -d
services:
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: cinema-frontend
    ports:
      # http://localhost:5174
      - "5174:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    container_name: cinema-backend
    command: npm run start:dev
    ports:
      - "3000:3000" 
    volumes:
      - ./backend:/usr/src/app 
      - /usr/src/app/node_modules 
    depends_on:
      - db 
    environment:

      DATABASE_URL: "postgresql://user:password@db:5432/cinema_db?schema=public"

  db:
    image: postgres:15 
    container_name: cinema-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  adminer:
    image: adminer
    container_name: cinema-adminer
    ports:
      - "8080:8080" # http://localhost:8080
    depends_on:
      - db

volumes:
  postgres_data: